// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBig9RB4FHN7uaw4GmUwQ9oaBhS_wUV2vs',
    appId: '1:1023001781018:web:d7a23ae6490d2360e3c2a3',
    messagingSenderId: '1023001781018',
    projectId: 'hommie-89',
    authDomain: 'hommie-89.firebaseapp.com',
    storageBucket: 'hommie-89.firebasestorage.app',
    measurementId: 'G-SZPJ953J53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6jfMjBe3SspjWP3kIGx4uTlpjx8JgqWQ',
    appId: '1:1023001781018:android:5d97c96aa510d21ae3c2a3',
    messagingSenderId: '1023001781018',
    projectId: 'hommie-89',
    storageBucket: 'hommie-89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8bMmXiEGHkMgLW-Xj2R2Q4z3Kv15z7go',
    appId: '1:1023001781018:ios:47a865bd0d24a697e3c2a3',
    messagingSenderId: '1023001781018',
    projectId: 'hommie-89',
    storageBucket: 'hommie-89.firebasestorage.app',
    iosBundleId: 'com.example.hommie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBig9RB4FHN7uaw4GmUwQ9oaBhS_wUV2vs',
    appId: '1:1023001781018:web:c029d932a62d0479e3c2a3',
    messagingSenderId: '1023001781018',
    projectId: 'hommie-89',
    authDomain: 'hommie-89.firebaseapp.com',
    storageBucket: 'hommie-89.firebasestorage.app',
    measurementId: 'G-E99CQDQY7J',
  );

}