final List<Map<String, dynamic>> sampleListings = [
  {
    'title': 'Cozy Bungalow',
    'location': 'Austin, TX',
    'price': 350000,
    'bedrooms': 2,
    'bathrooms': 1,
    'image': 'https://picsum.photos/400/300?1',
    'description': 'Charming 2 bed 1 bath in East Austin.',
    'locationKeywords': ['austin', 'tx', '78701'],
  },
  {
    'title': 'Modern Loft',
    'location': 'Brooklyn, NY',
    'price': 750000,
    'bedrooms': 1,
    'bathrooms': 1,
    'image': 'https://picsum.photos/400/300?2',
    'description': 'Industrial loft with skyline views.',
    'locationKeywords': ['brooklyn', 'ny', '11201'],
  },
  {
    'title': 'Beachside Villa',
    'location': 'Malibu, CA',
    'price': 2200000,
    'bedrooms': 4,
    'bathrooms': 3,
    'image': 'https://picsum.photos/400/300?3',
    'description': 'Gorgeous views and private beach access.',
    'locationKeywords': ['malibu', 'ca', '90265'],
  },
  {
    'title': 'Mountain Retreat',
    'location': 'Aspen, CO',
    'price': 1800000,
    'bedrooms': 3,
    'bathrooms': 2,
    'image': 'https://picsum.photos/400/300?4',
    'description': 'Ski-in/ski-out mountain retreat.',
    'locationKeywords': ['aspen', 'co', '81611'],
  },
  {
    'title': 'Suburban Dream Home',
    'location': 'Naperville, IL',
    'price': 620000,
    'bedrooms': 5,
    'bathrooms': 4,
    'image': 'https://picsum.photos/400/300?5',
    'description': 'Spacious family home with large backyard.',
    'locationKeywords': ['naperville', 'il', '60540'],
  },
  // Add more listings here if needed
];
